name: "grep for word"
on:
  push:
    branches:
      - dfgdfgdfg

jobs:
  grep:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Wrong domain check
        run: |
          echo "$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
          if git grep -q -E ${{ secrets.DOMAIN }} -- *.css; then
            echo "Game over man!"
            exit 1
          fi
