name: Push to live
on:
  push:
    branches:
      - main
jobs:
  push-to-live:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: "Github Action: Auto Commit"
          branch: live
          push_options: '--force'