name: "Check commit for word"
on:
  push:
    branches:
      - main

jobs:
  check_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Check commit
      uses: JJ/github-pr-contains-action@releases/v0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        bodyDoesNotContain: "dev.theme-park.dev"