name: Minify CSS and deploy to live branch
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@master
        with:
          js_engine: uglify-js

      - name: Remove .min suffix from minified files
        run: find ./CSS -depth -name "*.min.*" -exec sh -c 'mv "$1" "${1%.*.*}.${1##*.}"' _ {} \;

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          publish_dir: ./
          publish_branch: live
          github_token: ${{ secrets.GITHUB_TOKEN }}
