name: "Check commit for word"
on:
  push:
    branches:
      - main

jobs:
  yo_fuck_stick:
    runs-on: ubuntu-latest
    steps:
    - name: dev.theme-park.dev
      uses: actions/checkout@v2
    - name: get output
      id: slapAss
      run: |
        DIFF=$(git diff --color=always|perl -wlne 'print $1 if /^\e\[32m\+\e\[m\e\[32m(.*)\e\[m$/')
        echo "$DIFF"
        case "$DIFF" in 
          *dev.theme-park.dev*)
          echo "FUCK....ASS"
          echo '::set-output name=BITCH_PLEASE::true' 
            ;;
        esac
    - name: cancelling
      if: steps.slapAss.outputs.BITCH_PLEASE=='true'
      uses: andymckay/cancel-action@0.2